---
title: "Introduction to R"
output:
  word_document: default
  html_document: default
date: "2024-12-14"
---

# Introduction to R

```{r}
?sqrt
apropos("sq") # To search all function with keyword sq
```

```{r}
ls() # To list out all variable used
```

```{r}
rm(list=ls()) # to remove all variable in r
ls()
```

```{r}
getwd() # To show working directory
setwd() # To set working directory
```

```{r}
update.packages() # To update existing packages
```

```{r}
sqrt()
abs()
sin(), cos(), tan(),
pi
exp(), log(), # log() is natural log, ln
log10()
factorial()
choose() # combination
```

## Exercise 1

```{r}
1 + 2 * (3 + 4)
```

```{r}
sqrt((4 + 3) * (2 + 1))
```

```{r}
cos(4 * pi)
```

```{r}
log(0) # output: negative infinity
```

```{r}
factorial(6)
```

```{r}
choose(52,5)
```

```{r}
(1 + 2i) * (1 - 2i)
```

```{r}
sqrt(-1) #NaN is Not a Number
```

```{r}
sqrt(as.complex(-1))
```

## Vector

```{r}
x = c(1,3,5,7)
y = c(2,4,6,8)
z = c(x,y) # Concatenate vector
z
```

### Sequence

```{r}
50:89
```

```{r}
seq(0,1,0.1) # seq(start,end, step)
```

```{r}
seq(55,50,-0.3)
```

### Repetitive

```{r}
rep(3,5)
```

```{r}
rep(x,4)
```

```{r}
rep(x,c(2,5,1,3))
```

### Vector aritmethic

```{r}
x[-1]
```

```{r}
sum(x)
```

```{r}
cumsum(x)
```

```{r}
cumprod(x)
```

## Exercise 2

### Question 1

```{r}
x = c(2,5,4,10,8)
sqrt(x)
```

```{r}
x - 6 
```

```{r}
(x/10)^2
```

### Question 2

```{r}
sales = c(1,1,3,4,7,11)
length(sales)
```

```{r}
sum(sales)
```

```{r}
cumsum(sales)
```

```{r}
(sum(sales))^3
```

### Question 3

```{r}
y = c(3,6,14,90,54,2,8,65,28,45,7)
y > 30
```

```{r}
y[y<10]
```

```{r}
length(y[y<10])
```

```{r}
y[1:5] + 5
```

## Matrix

```{r}
y = c(3,6,14,90,54,2,8,65,28,45)
Y = matrix(y, nrow = 5)
Y
```

```{r}
X = matrix(y, nrow = 5, byrow = T)
X
```

```{r}
x = c(56,8)
y = c(2,16)
a = rbind(x,y)
b = cbind(x,y)
a
b
```

```{r}
dim(X)
```

```{r}
solve(a) # Inverse matrix
```

```{r}
det(a) # Determinant
```

```{r}
myscan
```

## Exercise 3

### Question 1

```{r}
q = c(4,6,8,2,3)
w = c(1,9,3,5,7)
e = c(6,4,2,7,1)
q1 = cbind(q,w,e)
dim(q1)
```

```{r}
q1 + 3
```

```{r}
q1_t=t(q1)
q1_t
```

```{r}
q1 %*% q1_t
```

### Question 2

```{r}
A = matrix(scan(), ncol = 4, byrow = T)
A
B = matrix(scan(), ncol = 4, byrow = T)
```

```{r}
b_inv = solve(B)
A %*% b_inv
```

```{r}
A %*% t(B)
t(A %*% B)
```

### Question 3

```{r}
R = matrix(scan(), nrow = 3, ncol = 3, byrow = T)
R
```

```{r}
R < 50
```

## Data Frame

```{r}
data() # To find available data to play around
```

```{r}
trees
```

```{r}
trees$Height
```

```{r}
attach(trees)
Height
```

```{r}
str(trees)
```

```{r}
mydata = data.frame()
mydata
```

```{r}
fix(mydata) # Fix data frame manually
mydata
```

### Tibble

```{r}
library(tidyverse)
```

```{r}
TREES = as_tibble(trees)
TREES
```

```{r}
diamonds
```

```{r}

```
